version: "3"
services:
  db:
    image: "postgres:10.3-alpine"
    restart: unless-stopped
    container_name: recommendations-db
    environment:
      - POSTGRES_USER=recommendations
      - POSTGRES_PASSWORD=secret123
      - POSTGRES_DB=recommendations
    ports:
      - "5324:5432"