# Generated by Django 2.2.6 on 2019-11-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_auto_20191113_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
